/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BigButton: typeof import('./src/components/BigButton.vue')['default']
    DrinkingWater: typeof import('./src/components/DrinkingWater.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    EyeProtection: typeof import('./src/components/EyeProtection.vue')['default']
    IEpCircleCloseFilled: typeof import('~icons/ep/circle-close-filled')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpCloseBold: typeof import('~icons/ep/close-bold')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpMinus: typeof import('~icons/ep/minus')['default']
    IEpRemoveFilled: typeof import('~icons/ep/remove-filled')['default']
    IEpSemiSelect: typeof import('~icons/ep/semi-select')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    IEpSwitchButton: typeof import('~icons/ep/switch-button')['default']
    IEpTools: typeof import('~icons/ep/tools')['default']
    IEpToos: typeof import('~icons/ep/toos')['default']
    Other: typeof import('./src/components/Other.vue')['default']
    Sedentary: typeof import('./src/components/Sedentary.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
