/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/appHeader.vue')['default']
    BigButton: typeof import('./src/components/BigButton.vue')['default']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    IEpArrowLeftBold: typeof import('~icons/ep/arrow-left-bold')['default']
    IEpCloseBold: typeof import('~icons/ep/close-bold')['default']
    IEpSemiSelect: typeof import('~icons/ep/semi-select')['default']
    IEpTools: typeof import('~icons/ep/tools')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
